### ISSUE TITLE
Note: Disable burst attack.

### ISSUE THREAD

**Issue by FakelsHub** [BGforgeNet/Fallout2_Party_Orders#2]
>Allow/forbid party members to use burst attacks. Forbidden by default.
When allowed, it doesn't mean that they will always use burst, only that they may.

Возможно вы не вкурсе.
Это отключает все/любые вторичные атаки, а не только стрельбу очередью.

**Comment by burner1024** [comment]
Нет, мы не в курсе, в доке же не написано.
Хотя, какие там атаки?
- У огнестрела либо есть очередь, либо нет.
- Ножом можно полоснуть или пырнуть, но там же разница только косметическая. Как и у супермолота. Копье, правда, можно метнуть вторичной атакой.
- С рукопашкой непонятно, у NPC появляются вообще продвинутые удары как у PC или нет.

По идее, можно применять настройку только когда огнестрел в руках, тогда побочек не должно быть.

**Comment by FakelsHub** [comment]
почему написано)
https://github.com/FakelsHub/sFall-ScriptEditor/blob/36f8be360da1bce582967f5a0cf8622bc751f39b/ScriptEditor/Descriptions/opcodes_rus.txt#L877
Читай русские описания там более правильное описание функций. (английские описания я не поддерживаю).

Ладно я уже исправил/переделал действовать теперь будет только на оружие со стрельбой очередью.

**Comment by burner1024** [comment]
В апстрим-то попадет фикс?

**Comment by FakelsHub** [comment]
что значит попадет в апстрим?
Я как бы в sfall исправил функцию.

**Comment by burner1024** [comment]
Ну ты в своем форке исправил же? В https://github.com/phobos2077/sfall попадет?

**Comment by NovaRain** [comment]
Yes.
