### ISSUE TITLE
[Feature Request] Command party to wait

### ISSUE THREAD

**Issue by WebTiger89** [BGforgeNet/Fallout2_Party_Orders#3]
It would be really handy if it's possible to command all members to wait at once. There are often situations where it's necessary to make them wait and it's annyoing to go through the dialogs for every member.

**Comment by burner1024** [comment]
Probably.
But getting them back into party will be 1 by 1 still.

**Comment by WebTiger89** [comment]
Still better as doing everything ba hand. Maybe it's also possible to let them join again by command?
1 command to make them wait.
1 command to let them join again.

**Comment by burner1024** [comment]
You can never know if you made someone wait personally, or en mass.
In addition, your stats and other conditions may not be the same as when you left them, so you may be not eligible for having the same amount of party members.

**Comment by burner1024** [comment]
Extract this into `data/scripts` to try. 
[gl_p_party_orders.int.zip](https://github.com/BGforgeNet/Fallout2_Party_Orders/files/8332739/gl_p_party_orders.int.zip)

Also need [this](https://github.com/BGforgeNet/Fallout2_Party_Orders/blob/b183a6456fc3bb03b5304fe5181682d50289198e/mods/party_orders.ini#L27-L28) added to ini to work.
Make sure to check that car trunk doesn't get lost.

And there's problem of temporary party members such as Bess, Laddie, etc. They don't really have a dialog to re-join if dropped.

**Comment by WebTiger89** [comment]
@burner1024 Does not work. When pressing Ctrl + W, "Error" message occurs above the character and it seems the state of the party members is resetted: the dialog options are like before I hired them to join the party.

Thanks for investigation so far!

**Comment by burner1024** [comment]
Error message is normal, it's just missing the new [text](https://github.com/BGforgeNet/Fallout2_Party_Orders/blob/877e7425fc775d85634948f7543e937c0dae6c51/data/text/english/game/p_party_orders.msg#L69).
Resetting dialog is not. Try this [gl_p_party_orders.int.zip](https://github.com/BGforgeNet/Fallout2_Party_Orders/files/8355094/gl_p_party_orders.int.zip).

**Comment by WebTiger89** [comment]
I forgot to mention:
> In addition, your stats and other conditions may not be the same as when you left them, so you may be not eligible for having the same amount of party members.

This applies even without the script. Or do you mean the script cannot predict that for the rejoin? That would be indeed a problem. How did you solve it?

> You can never know if you made someone wait personally, or en mass.

Yeah it just handles this single use case if you need to have them wait **all**.

> Try this gl_p_party_orders.int.zip

Excellent work. Just one issue: Skynet Roboter still follows. You said some party members can't wait because they can't rejoin but Skynet can rejoin. I gues you have hard coded a list of members who are affected by the script. Can you add Skynet?

**Comment by burner1024** [comment]
> This applies even without the script. Or do you mean the script cannot predict that for the rejoin? That would be indeed a problem. How did you solve it?

I didn't, thus no mass rejoin.

**Comment by burner1024** [comment]
Try this for brainbot fix 
[gl_p_party_orders.int.zip](https://github.com/BGforgeNet/Fallout2_Party_Orders/files/8402403/gl_p_party_orders.int.zip)

**Comment by Artofeel** [comment]
brainbot stiil doesn't work
seems like there is no LVAR_WAITING for it (wcbrnbot script doesn't use it at all)
and you sure you're used correct PID?
PID_BRAINBOT vs PID_ROBOBRAIN

**Comment by burner1024** [comment]
Don't know, try this 
[gl_p_party_orders.int.zip](https://github.com/BGforgeNet/Fallout2_Party_Orders/files/8839854/gl_p_party_orders.int.zip)

**Comment by Artofeel** [comment]
same...
for me it's `PID_ROBOBRAIN_HUMAN`
so, need a gamesave with cybernetic brait bot to check either this `PID_ROBOBRAIN` or `PID_BRAINBOT`
anyway if you check `wcbrnbot` script, procedure `timed_event_p_proc`, you will see that there is no `game_time` value for `set_local_var`
it's just uses
```
set_local_var(12, 0);
set_local_var(8, 1);
```
12 is `LVAR_In_Party`
8 is `LVAR_Wait`
probably...

**Comment by Artofeel** [comment]
and about command to re-follow
just remember who is set to wait and then command to follow again one by one to the limit

**Comment by burner1024** [comment]
ok, doesn't work, so disabled.
