### ISSUE TITLE
Vic won't lockpick

### ISSUE THREAD

**Issue by Owyn** [BGforgeNet/Fallout2_Party_Orders#4]
I played 1st fallout and Kat'ja lockpicked for me when I pressed 2 but Vic in 2nd fallout won't, what's the problem? Can there maybe be a hotkey for party members made to lockpick\repair?

**Comment by burner1024** [comment]
Probably your skill is higher.

**Comment by Owyn** [comment]
My lockpick skill is 13% and Vic's one is said to be 100% ( https://fallout.fandom.com/wiki/Vic#Statistics )
![image](https://user-images.githubusercontent.com/1309656/216790373-e3bdea3b-f651-48ca-8949-fb1fc49eb7ad.png)

**Comment by Owyn** [comment]
some article on the internet says that by default party members can only use one skill they "specialize in" ( https://tvtropes.org/pmwiki/pmwiki.php/YMMV/Fallout2 )

so "fixing" it could be a great addition to Party Orders mod

**Comment by burner1024** [comment]
It may be something in sfall or another mod. Check nma too.

**Comment by burner1024** [comment]
Party members can only help the player in active skill use if the highest skill in the party is also that member's "tagged skill" (i.e. highest skill displayed on their combat perf panel).
I was doing something about that in [FO2tweaks](https://github.com/BGforgeNet/FO2tweaks/blob/master/source_test/gl_g_party_skills.ssl), but it never got completed.

**Comment by Owyn** [comment]
yea, for some reason there's a separate check after checking who has the highest skill to see if it's his best skill among his skills: https://github.com/alexbatalov/fallout2-re/blob/f194c2e75bcbff4f39aab76860f78269b6bb7c13/src/game/actions.c#L1425

I `nop`ed that check and now Sulik checks for traps for me and Vic does lockpicks and science actions just fine: 

![image](https://user-images.githubusercontent.com/1309656/216817758-93221969-c1f3-4088-8080-2fb54bcd74ea.png)
![image](https://user-images.githubusercontent.com/1309656/216817821-fd8a72e1-e42d-4cf8-942b-dedcb261a284.png)

set these two bytes to `90` (sfall scripts can do that with `write_byte` I think)
![image](https://user-images.githubusercontent.com/1309656/216817948-43f3a2f3-2be0-4178-9c9b-38dd0ddc648d.png)

but what about lockpick and "tool" items? wiki says for their +20% bonus to work you need to specifically use those items on doors\objects, - can you perhaps account having those items in your\your party's member inventory and just add their bonus when an according skill is used (without having to use items on objects each time)?

**Comment by burner1024** [comment]
Yes it can all be scripted, but I've no plans to work on it.
