### ISSUE TITLE
Bursts disabled by default leads to confusion

### ISSUE THREAD

**Issue by phobos2077** [BGforgeNet/Fallout2_Party_Orders#5]
I think disabling bursts as a default state is a mistake. This leads to thinking there's something wrong with the game, checking party member combat settings etc. People get this mod by default with RPU. I think mod like this should be non-intrusive opt-in experience. 

On other note, I also suggest to add Ctrl modifier to every hotkey to avoid possible conflicts. Seems like more frequently used hotkeys can conflict with this, which is less often used, especially early game before you even have any party. For example, use R to reload (I like to manually press it to reload, no autoreloading).

**Comment by burner1024** [comment]
Allowed burst, but hotkeys are fine I think.
