### ISSUE TITLE
Not working in Fallout et tu

### ISSUE THREAD

**Issue by courrier1** [BGforgeNet/Fallout2_Party_Orders#6]
Hey there
I saw this mod recommended in [Fallout1in2](https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/README.md#additional-mods) I've downloaded it, extracted the files in main dir and nothing changed, is there something I'm missing?

**Comment by burner1024** [comment]
Probably wrong directory, show full paths.

**Comment by courrier1** [comment]
Both "party_orders.dat" and "party_orders.ini" are next to the game exe file.

**Comment by burner1024** [comment]
They should be in mods directory.

**Comment by courrier1** [comment]
I have done that too, but it didn't work. Can you give more details, like do you put them directly in mods folder.
Here is what I tried: 
moving the two files next to the exe file, so they it can be loaded similar to HighRes patch, but it didn't work.
moving the two files into mods folder, it didn't work. I then put them inside party_orders folder in mods and added the name to mods_order.txt, still nothing works.

**Comment by courrier1** [comment]
@burner1024 
It is working now, the solution is to add "party_orders.dat" in mods_order.txt

**Comment by burner1024** [comment]
Right, newer sfall requires that.
